# fly.toml app configuration file generated for livedraft on 2023-08-04T11:18:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "livedraft"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
